Cargo.toml
Cargo.toml required a reordering.
=> Formatting Cargo.toml for movementlabsxyz/movement by category with subcategory alphabetical ordering.

.github/workflows/containers.yml, scripts/docker/build-push-image, scripts/movement/build-push-image
- **Categories**: `scripts`, `cicd`.
Various improvements in the CI workflow and scripts for building containers.
CI should pass. The scripts that have failing commands inside them should fail, or not be invoked
(the container workflows are currently disabled?)
=> CI cleanup for containers

protocol-units/settlement/mcr/contracts/src/token/locked/LockedToken.sol, protocol-units/settlement/mcr/contracts/test/token/locked/LockedToken.t.sol, protocol-units/settlement/mcr/contracts/test/token/stlMoveToken.t.sol
small optimization green lit late today
loop and check for simple smaller than instead of smaller or equal to
test has been updated to reflect it
=> fix loop and tests

docs/movement-node/indexer-explorer/README.md
Indexer and Explorer onboarding documentation, kudos @andygolay
=> doc: indexer and explorer onboard

README.md, docker/README.md, justfile, networks/README.md, scripts/README.md, scripts/movement/docker-compose, scripts/movement/native, scripts/movement/run
Updates documentation to better specify scripting flow, particularly w.r.t. `docker-compose`. 
1. Numerous cosmetic changes to `./scripts/movement/*`.
2. Changes to READMES throughout the repo.
1. Tests preserved.
1. `nix` directory is still undocumented.
2. `types` directory is still undocumented.
=> Docs Update

README.md
found a minor typo spelling in your doc.
Hope it helps.
=> fix link README.md

docs/movement-node/run/manual/README.md, networks/README.md, protocol-units/cryptography/tentacles/proptest-regressions/tests/jellyfish_merkle.txt
Hello
I rectify some typographical inaccuracies.
Hope it helps
Br, Elias.
=> fix: spelling issues

docs/movement-node/run/manual/README.md
Brief instruction to launch as an attester
=> feat: attester launch

protocol-units/bridge/shared/src/blockchain_service.rs, protocol-units/bridge/shared/src/bridge_contracts.rs, protocol-units/bridge/shared/src/bridge_monitoring.rs, protocol-units/bridge/shared/src/bridge_service.rs, protocol-units/bridge/shared/src/bridge_service/active_swap.rs, protocol-units/bridge/shared/src/bridge_service/events.rs, protocol-units/bridge/shared/src/types.rs, protocol-units/bridge/shared/tests/abstract_blockchain.rs, protocol-units/bridge/shared/tests/blockchain_service.rs, protocol-units/bridge/shared/tests/bridge_service.rs, protocol-units/bridge/shared/tests/bridge_service_error_handling.rs, protocol-units/bridge/shared/tests/shared/mod.rs, protocol-units/bridge/shared/tests/shared/testing/blockchain.rs, protocol-units/bridge/shared/tests/shared/testing/blockchain/client.rs, protocol-units/bridge/shared/tests/shared/testing/blockchain/counterparty_contract.rs, protocol-units/bridge/shared/tests/shared/testing/blockchain/initiator_contract.rs, protocol-units/bridge/shared/tests/shared/testing/mocks.rs
This pull request introduces several significant changes to the blockchain service modules associated with the bridge protocol. The primary focus of this update is enhancing the parameter types for better type safety and handling in bridge-related operations, including initiating transfers and processing contract events. 
- Updates to type parameters in `ContractEvent`, defining more stringent relationships between attributes.
- Modifications to `complete_bridge_transfer` and related functions to utilize updated `RecipientAddress` and `InitiatorAddress` types ensuring better encapsulation.
- Enhancement of underlying type constraints within blockchain service classes for improved data handling.
- Addition of new conversion traits to facilitate seamless …
=> ENG-672 added initiator address and conversion traits

README.md, docs/movement-node/run/ansible/suzuka-full-node.service.j2, docs/movement-node/run/manual/README.md, docs/movement-node/run/manual/suzuka-full-node.service.template
Updated the paths for the docker compose files.  Potential fix for https://github.com/movementlabsxyz/movement/issues/199
Updated the paths for the docker compose files used
=> fix: update compose paths

Cargo.lock, protocol-units/mempool/move-rocks/Cargo.toml, protocol-units/mempool/move-rocks/src/lib.rs
This an updated version of https://github.com/movementlabsxyz/movement/pull/251
which was opened around the same time of a merge which affected the `move-rocks` lib.
I opted to create a new branch (old one is deleted).
Updated to be consistent with main
All unit tests pass
Benchmarking could be good to to ensure it indeed provides a performance boost.
=> Update: replace serde_json with bcs in move-rocks

Cargo.lock, protocol-units/execution/dof/Cargo.toml, protocol-units/execution/dof/src/v1.rs, protocol-units/execution/opt-executor/src/executor/execution.rs, protocol-units/execution/opt-executor/src/executor/initialization.rs, protocol-units/execution/opt-executor/src/executor/mod.rs, protocol-units/execution/opt-executor/src/executor/transaction_pipe.rs
=> Mempool Lock

.github/workflows/checks.yml
These got accidently deleted during a merge conflict fix.
Adds back Sol tests in CI Checks
- CI should pass
=> Sol tests to run in CI

networks/suzuka/suzuka-full-node/src/partial.rs
=> fix: transactions in flight.

protocol-units/settlement/mcr/contracts/src/staking/MovementStaking.sol, protocol-units/settlement/mcr/contracts/src/staking/interfaces/IMovementStaking.sol, protocol-units/settlement/mcr/contracts/src/token/custodian/CustodianToken.sol, protocol-units/settlement/mcr/contracts/test/staking/MovementStaking.t.sol, protocol-units/settlement/mcr/contracts/test/token/custodian/CustodianToken.t.sol, protocol-units/settlement/mcr/contracts/test/token/stlMoveToken.t.sol
https://github.com/movementlabsxyz/movement-private/pull/13
=> fix: remove unrelated changes.

.github/workflows/build-push-containers-all.yml, .github/workflows/checks-all.yml
=> fix: better matching.

networks/suzuka/suzuka-full-node/src/tasks/execute_settle.rs
=> Reinclude Decrement Transactions In Flight.

protocol-units/settlement/mcr/contracts/test/settlement/MCR.sol
Refactors MCR test to include upgradeable proxy pattern.
* adds a setup and removes repeated logic.
* changed the acceptGenesisCeremony() call to be initiated by controller, not a call from mcr.
All tests passing
=> Add upgradeable proxies to MCR

.github/workflows/checks-all.yml
Added bridge label to `solidity-bridge-tests` workflow.
```
solidity-bridge-tests:
if: contains(github.event.label.name, 'bridge') 
```
Hope it passes CI
=> feat: add bridge label to workflow

.gitmodules
=> Re import submodule to support the same module twice.

docker/compose/suzuka-indexer/README.md, docker/compose/suzuka-indexer/docker-compose.indexer.yml
Update hasura config to use an admin password and required env var to set JWT auth
=> Radu update hasura config

docker/compose/suzuka-indexer/docker-compose.indexer.yml
update indexer postgres config
=> update indexer postgres config

protocol-units/bridge/integration-tests/tests/bridge_e2e_test.rs, protocol-units/bridge/service/src/chains/ethereum/event_monitoring.rs
=> Bridge, use rpc for eth event monitoring

protocol-units/bridge/move-modules/sources/MOVETH.move
- Efficiency improvements based on #626 
In `moveth.move`: update `assert_not_paused` and `moveth_address` functions per @franck44's observations (see #626)
Unit tests pass with `aptos move test`
=> Feat: Efficiency improvements 

docker/compose/bridge/docker-compose.eth-holesky.yml, docker/compose/bridge/docker-compose.mvt-bardock.yml
=> Holesky and Bardock Overlays for Convenience

protocol-units/bridge/service/src/lib.rs
To avoid sending 2 Tx at the same time to the same client, which could possibly generate a nonce error, Tx are synchronized per client.
The bridge e2e test Eth->Mvt direct pass.
I didn't test using concurrent Tx. It needs to develop more testing code to test the relayer logic.
=> Bridge Synchronize tx send to both client.

docker/compose/suzuka-indexer/README.md, docker/compose/suzuka-indexer/docker-compose.indexer.yml
Add some docs about hasura metadata
=> use builtin role anonymous that can be set automatically

protocol-units/bridge/service/src/chains/ethereum/client.rs, protocol-units/bridge/service/src/chains/ethereum/utils.rs
=> Bridge add sender trace to lock_transfer

docker/compose/suzuka-indexer/docker-compose.indexer.yml
Fix: fix: set and expose indexer health check
=> fix: set and expose indexer health check

protocol-units/bridge/indexer-db/src/client.rs
=> Bridge Config

protocol-units/execution/opt-executor/src/executor/initialization.rs, protocol-units/execution/util/src/config/chain.rs, protocol-units/execution/util/src/config/common.rs, protocol-units/execution/util/src/config/mempool.rs
=> feat: pruner config redux.

protocol-units/sequencing/memseq/sequencer/src/lib.rs
Resolves #882 
1. Adds units test to check that the parent block is properly updated. 
1. This is fairly trivial. But, it would be nice to have this race condition be checked by tests or verification someday.
=> Fix Race Condition in Block Building

protocol-units/da/movement/celestia/light-node/src/v1/sequencer.rs
Resolves #878 
1. Adds unit test to check the splitting implementation results in the correct split blocks. 
None
=> Fixes Block Splitting Implementation Used in Heuristic for Celestia Submission

protocol-units/bridge/integration-tests/tests/client_mvt_tests.rs
Updates the `Nonce` value to 1. Note Auto-formatting was applied, not sure why it was formatting to other settings, double check your IDE to make sure the fmt settings we have in the workspace are being applied. 
We can't generate it in the same way as the Eth client test as the nonce it is asserting against is fetched from the emitted event. 
A developer has the node running and repeatedly runs the same integration test over and over.  
I wasn't actually able to run the test locally due the integration test randomly hanging forever. But this was the what the assertion was looking for so it should pass. Let's get CI up to remove this burden of having to run all this locally cc @andygolay 
- Update the Nonce
1. 
```
CELESTIA_LOG_LEVEL=FATAL CARGO_PROFILE=release …
```
=> Fix mvmt client test 

docker/compose/movement-indexer/docker-compose.indexer.yml, networks/movement/indexer/src/main.rs
- **RFCs**: na.
- **Categories**: `networks`
custom built docker image and test
=> Don't hardcode db name, which should be in connection string

protocol-units/settlement/mcr/contracts/src/settlement/MCR.sol
=> Mainnet Target Branch

docker/build/movement-indexer/Dockerfile
- **RFCs**:  na
- **Categories**: `scripts`.
=> Put `load_metadata` binary into movement-indexer image

util/signing/interface/src/key/mod.rs
Add testnet as environment possibility. 
Rename devNet to devnet.
=> [Signing] add testnet in key name environement

Cargo.lock, util/signing/interface/src/key/mod.rs, util/signing/providers/hashicorp-vault/Cargo.toml, util/signing/providers/hashicorp-vault/src/hsm/key.rs, util/signing/providers/hashicorp-vault/src/hsm/mod.rs
Change Hashicorp Vault delimiter from a _ to a - 
Add some logs to see the generated key.
=> [Signing Change Hashicorp Vault delimiter to a -

protocol-units/settlement/mcr/contracts/src/settlement/MCR.sol, protocol-units/settlement/mcr/contracts/src/staking/MovementStaking.sol, protocol-units/settlement/mcr/contracts/src/staking/MovementStakingStorage.sol, protocol-units/settlement/mcr/contracts/src/staking/interfaces/IMovementStaking.sol, protocol-units/settlement/mcr/contracts/test/settlement/MCR.sol, protocol-units/settlement/mcr/contracts/test/staking/MovementStaking.t.sol
changes variable names for staking
=> StakeForAcceptingEpoch and CustodianStake

Cargo.toml
- Updates aptos-core to latest rev from `movement`
=> chore: update aptos core rev

.github/workflows/build-push-containers-all.yml, .github/workflows/checks-all.yml
=> fix: build on tag

protocol-units/execution/maptos/opt-executor/src/background/transaction_pipe.rs, protocol-units/execution/maptos/opt-executor/transaction-pipe.md
=> chore: cherry pick from 1080

process-compose/movement-full-node/process-compose.hasura.yml, process-compose/movement-full-node/process-compose.indexer-test.yml
Correct the indexer e2e Test
```
CELESTIA_LOG_LEVEL=FATAL nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash  -c "just movement-full-node native build.celestia-local.indexer.hasura.indexer-test --keep-tui"
```
=> fix: correct indexer test

networks/movement/movement-client/src/bin/e2e/followers_consistent.rs, process-compose/movement-full-node/process-compose.test-followers.yml
-  make `test-followers-consistent` pass
- Fund Alice with leader node (still choose random node for subsequent transactions)
- Add `MOVEMENT_SYNC` env var to `test-followers-consistent`
```
CELESTIA_LOG_LEVEL=FATAL nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash  -c "just movement-full-node native build.setup.eth-local.celestia-local.test-followers --keep-tui"
```
=> fix: test-followers-consistent

networks/movement/movement-client/src/bin/e2e/load_alice_bob.rs, networks/movement/movement-full-node/src/node/tasks/execute_settle.rs, protocol-units/execution/maptos/opt-executor/src/bootstrap.rs, scripts/services/movement-full-node/build
Minor quality of life improvements done while doing load and soak testing (#1204).
=> chore: logging cleanups, CARGO_PROFILE for node build

protocol-units/execution/maptos/framework/releases/pre-l1-merge/src/lib.rs
Simply exposing some types to facilitate a `movement-migration` example.
=> chore: expose aptos framework release util.

.github/workflows/build-push-container.yml, .github/workflows/build-push-containers-all.yml
=> fix(cicd): move condition check for build in reusable workflow

docker/compose/movement-full-node/snapshot/docker-compose.backup.yml, docs/movement-node/run-fullnode/scripts/devnet/backup.sh
=> update restic to use credentials inherited from ec2 instance

docker/compose/movement-full-node/snapshot/docker-compose.restore.yml, docs/movement-node/run-fullnode/README.md, docs/movement-node/run-fullnode/ansible/devnet/README.md, docs/movement-node/run-fullnode/ansible/devnet/movement-fullnode.yml, docs/movement-node/run-fullnode/ansible/mainnet/README.md, docs/movement-node/run-fullnode/ansible/mainnet/movement-fullnode.yml, docs/movement-node/run-fullnode/ansible/testnet/README.md, docs/movement-node/run-fullnode/ansible/testnet/movement-fullnode.yml
Add the remarks and issues that all partner noted during hte upgrade.
=> feat: da sequencer, update docs with upgrade remarks

.github/workflows/build-push-containers-all.yml, docker/build/movement-indexer-v2/Dockerfile, docker/compose/movement-indexer/docker-compose.local-development.indexer-v2.yml
- **Categories**:  `misc`.
Add docker file to run indexer v2. 
Locally tested and the processor runs and hitting data issue. This is due to fullnode is not setup correctly. Fix will be put in the next PR.
=> [feat] Add indexer v2 docker file(3/n)

Cargo.lock, Cargo.toml, protocol-units/execution/maptos/util/Cargo.toml, protocol-units/execution/maptos/util/src/config/common.rs, protocol-units/execution/maptos/util/src/config/health_server.rs, protocol-units/execution/maptos/util/src/config/metrics_server.rs, protocol-units/execution/maptos/util/src/config/mod.rs, util/health/Cargo.toml, util/health/src/lib.rs, util/tracing/Cargo.toml, util/tracing/src/lib.rs, util/tracing/src/simple_metrics.rs
- **RFCs**: https://github.com/movementlabsxyz/movement/issues/1258
- **Categories**:  `util`
* Add simple components for health + metrics server. 
* We use a different approach that drives the processors and there is no metrics component in v2. To support the metrics, we create a component here.
* Add health check and metrics endpoint component. 
Locally tested and looks good! 
* Metrics
* Health check
=> [feat] add metrics+health server component for indexer v2 (1/n)

protocol-units/execution/maptos/framework/releases/README.md
Add a table that identifies all features with different statuses between the Aptos and Mvt networks.
Define the features that have the same state but must also be changed.
This table must be reviewed and completed to indicate the value of all features in the L1 network after migration.
Readme file that identifies the feature to change.
No test needed.
=> Features to activate / deactivate
