Cargo.lock
networks/monza/monza-full-node/src/partial.rs
protocol-units/execution/monza/executor/src/lib.rs
protocol-units/execution/monza/executor/src/v1.rs
protocol-units/execution/monza/opt-executor/src/executor.rs

While investigating the transaction confirmation bug, I eventually discovered that our executor is actually not committing state successfully. Sorry, I should have reviewed that more closely in #30 .
It turns out the issue I was experiencing is not due to our current `monza-opt-executor` failing to move transactions from pending. But, instead, it is a result of state not being reliably committed at all. 
Check out the tests in the [`monza-opt-executor` ](https://github.com/movementlabsxyz/movement/tree/partial-monza/broken-executor/protocol-units/execution/monza/opt-executor) crate. 
In particular, I've expanded **`test_execute_block_state_db`** to actually run checks of state values with the state view, and it has not passed. 
Strangely, you can successfully get transactions from the …

Broken Monza Executor

---

networks/monza/monza-full-node/src/partial.rs
networks/suzuka/suzuka-full-node/src/partial.rs
protocol-units/execution/maptos/opt-executor/src/executor.rs
protocol-units/execution/maptos/util/src/finality_mode.rs
protocol-units/execution/monza/executor/src/lib.rs
protocol-units/execution/monza/executor/src/v1.rs
protocol-units/execution/suzuka/executor/src/lib.rs
protocol-units/execution/suzuka/executor/src/v1.rs

Make `FinalityMode` passed by value like a simple mode selector parameter should be.
Change signatures of methods that don't need to be async
or fallible.

Executor API cleanup and simplification

---

protocol-units/settlement/mcr/contracts/src/MCR.sol

- **Status**: `draft`
- **RFCs**: [RFC MCR Draft](https://github.com/movementlabsxyz/rfcs/pull/29)
Adds block height to `BlockAccepted` event in MCR smart contract. 
- Adds block height to `BlockAccepted` event in MCR smart contract. 
MCR tests unaltered. 
- Tests could be added to check that event is emitted.

feat: add block height to BlockAccepted.

---

Cargo.lock
protocol-units/sequencing/memseq/Cargo.toml
protocol-units/sequencing/memseq/src/lib.rs

- **rustfmt**
- **test(memseq): add initialization unit test**
- **test(memseq): Add tests for with_block_size and with_building_time_ms methods**
- **test(memseq): Add new unit tests for try_move_rocks function**
- **test(memseq): Add test for waiting on next block with no transactions**
- **test(memseq): add support for concurrent access testing**
- **test(memseq): add tests for error propagation in `Memseq` operations**
- **test(memseq): add test for block building timeout**
- **Status**: `review`
1. Updated the test suite to cover scenarios involving testing memseq concurrency control mechanisms.
2. Added `futures` to dev-dependencies in `Cargo.toml` and `Cargo.lock` to test asynchronous operations using FuturesUnordered.
3. Made syntax and format …

ENG 394 additional unit test for memseq

---

networks/monza/monza-full-node/src/partial.rs
networks/suzuka/suzuka-full-node/src/partial.rs
protocol-units/execution/maptos/util/src/finality_mode.rs
protocol-units/execution/maptos/util/src/lib.rs
protocol-units/execution/monza/executor/src/lib.rs
protocol-units/execution/monza/executor/src/v1.rs
protocol-units/execution/suzuka/executor/src/lib.rs
protocol-units/execution/suzuka/executor/src/v1.rs

The dynamic selector of finality modes is a vestige,
remove it making the internal composition of executors static.
- Removed the `FinalityMode` dynamic selector from executor interfaces.
Existing tests need to pass after code refactoring.

ENG-446 Remove FinalityMode

---

protocol-units/execution/maptos/opt-executor/src/executor.rs
protocol-units/execution/monza/executor/src/v1.rs
protocol-units/execution/monza/fin-executor/src/executor.rs
protocol-units/execution/suzuka/fin-executor/src/executor.rs

`DbReaderWriter` itself is two (ludicrously redundant) `Arc` pointers, so it's cheaply cloneable and generally, there's no need to guard or share this object.
To be further fixed some day: https://github.com/aptos-labs/aptos-core/issues/13464
- Simplified management of `DbReaderWriter` handles inside executor state.
Existing tests pass after the refactoring.

Remove `Arc<RwLock<_>>` around `DbReaderWriter`

---

.github/pull_request_template.md

As currently intended, the Status text field will duplicate the actual status as managed by GitHub, so it's either double work or prone to be out of date.

chore: remove Status field from PR template

---

docker/build/faucet/Dockerfile
nix/aptos-faucet-service.nix

- **Categories**: `cicd`
Image size for `aptos-faucet-service` was > 1GB which is now 146MB
- Used ldd to build dependency tree

Reduce faucet image size

---

nix/m1-da-light-node-relative-paths.patch
nix/m1-da-light-node.nix

- **Categories**: `cicd`.
- Updated `nix/m1-da-light-node.nix` to fix crane build
- Added `nix/m1-da-light-node-relative-paths.patch` to patch `movementxyz/aptos-core` deps
I don't currently know enough about the project to perform adequate testing of the resulting binary, but when run with no args it returns `Error: Token not provided`.

Fix Nix/Crane build of `m1-da-light-node`

---

Cargo.lock
Cargo.toml
networks/suzuka/setup/Cargo.toml
networks/suzuka/setup/src/local.rs
protocol-units/settlement/mcr/setup/Cargo.toml
protocol-units/settlement/mcr/setup/src/lib.rs
protocol-units/settlement/mcr/setup/src/local.rs

Add micro-crate `mcr-settlement-setup` to provide
setup infrastructure for MCR settlement configurations. 
Use it in suzuka-full-node-setup.
* Added crate `mcr-settlement-setup`.
None added. The crate will be used by the e2e tests.

mcr-settlement-setup: new crate

---

.github/workflows/build-push-containers.yml
.github/workflows/checks.yml
protocol-units/execution/opt-executor/src/executor/initialization.rs

Adds graceful restarts for Aptos execution, i.e., can start from the current DB. 
We still create a new DA network. I will try to address this in a forthcoming PR, but it is more involved. However, it doesn't matter for the current deployment which has one node because heights are assigned by the executors themselves and settled on. 
This would matter if nodes were started at different times and on different networks because then the bootstrapping would potentially miss transactions from one network (ofc). 
Excluding fixes to the DA to keep this PR small. 
1. Very small change to …

Graceful Restarts for Aptos Execution

---

.github/workflows/checks.yml
Cargo.lock
protocol-units/da/m1/light-node-verifier/Cargo.toml
protocol-units/da/m1/light-node-verifier/src/v1.rs
protocol-units/execution/dof/src/v1.rs
protocol-units/execution/fin-view/src/fin_view.rs

Update the tests in workspace crates that had compilation failures
because they needed adaptation to the new config and setup APIs,
so that the tests build.
`cargo check --all-targets`
`cargo check -p m1-da-light-node-verifier --tests --features integration-tests`
No effort to make the updated tests pass yet.
This change is only to resolve build failures in `cargo check --all-targets` that is used by IDEs to show build problems.
Need to produce workable test setups and add test runs to the CI so that the crate tests are run. This should be a subject for a separate planned task.

chore: update tests in the workspace to compile

---

Cargo.lock
networks/suzuka/suzuka-full-node/Cargo.toml
networks/suzuka/suzuka-full-node/src/lib.rs
networks/suzuka/suzuka-full-node/src/main.rs
networks/suzuka/suzuka-full-node/src/manager.rs

- **RFCs**: $\emptyset$
Uses `godfig` with manger pattern to run Suzuka Full Node.
1. Uses `godfig::try_wait_for` to await the appropriate config setting in Suzuka. 
1. `just suzuka-full-node native build.setup.test.local`. 
1. Still starts services one after another. This will not be modified until Suzuka Full Node go around. 
2. More clean can be cone, but pausing here to keep PR smallish.

feat: suzuka with manager and godfig.

---

networks/suzuka/suzuka-full-node/src/partial.rs

Quick fix for busy loop in suzuka-full-node

---

Cargo.lock
Cargo.toml

Brings in the latest commit on from aptos-core suzuka (the latest known commit with the patch fix added)
https://github.com/movementlabsxyz/aptos-core/commits/suzuka/
- Updates the rev tag for all aptos dependencies, https://github.com/movementlabsxyz/aptos-core/commit/6b1e45dc58d4a1e95b8b8a7356fa721f30a48e2d
- Tested manually here https://github.com/movementlabsxyz/movement/pull/179

Update aptos-core version for the faucet sequencing fix

---

Cargo.lock
Cargo.toml
flake.lock
flake.nix
protocol-units/execution/dof/src/v1.rs
protocol-units/execution/fin-view/src/fin_view.rs
protocol-units/execution/opt-executor/src/executor/execution.rs
rust-toolchain.toml

Supersedes #158
- **Categories**: `protocol-units`, `misc`.
Update to the changes in https://github.com/movementlabsxyz/aptos-core/pull/30
* The aptos-core forked crates have been updated to upstream commit 1dfd8a85c412dd08d4a61afd9e72475f54319db4 and aptos-cli 3.5.0
Updated tests should pass in CI.

Sync with upstream

---

protocol-units/settlement/mcr/contracts/src/staking/MovementStaking.sol
protocol-units/settlement/mcr/contracts/src/staking/MovementStakingStorage.sol
protocol-units/settlement/mcr/contracts/src/staking/interfaces/IMovementStaking.sol
protocol-units/settlement/mcr/contracts/test/settlement/MCR.sol
protocol-units/settlement/mcr/contracts/test/staking/MovementStaking.t.sol

- **Categories**: any of `protocol-units`
In order to gate the attesters on our network a whitelist is being used to prevent those not in this list to stake/unstake and hence not become attesters.  Technically one could just gate `stake` but for completeness `unstake` is also gated with the list.
Includes changes to the storage for the whitelist of addresses, setters and modifier.
Tests have been added to cover the whitelist functionality and have been updated where `stake` is being used as now each staker has to be whitelisted.

feat: whitelist staking

---

Cargo.lock
Cargo.toml
protocol-units/execution/opt-executor/Cargo.toml
protocol-units/execution/opt-executor/src/executor/transaction_pipe.rs

When executing the malicious Test, the Suzuka behavior was different from the Aptos node. Some Tx issues were not detected during submission and the client was waiting indefinitely because the execution error weren't seen.
This PR add Tx pre execution when the Tx is submitted.
From the test I've done, the node behavior is the same as the Aptos node.
For example: 
* INVALID_AUTH_KEY and BAD_CHAIN_ID return during the Tx submission.
* INSUFFICIENT_BALANCE and WRONG ARGUMENTS return during the Tx waiting.
To run the Suzuka node use:
```
CELESTIA_LOG_LEVEL=FATAL nix develop --extra-experimental-features …
```

add Tx pre execution when submited

---

protocol-units/bridge/move-modules/sources/atomic_bridge.move

Bridge move modules package was compiling and passing tests but not publishing. It was because `init_module` in `atomic_bridge::atomic_bridge_counterparty` can only take 1 arg. Module tests were not exposing the error for some reason. 
I modified `init_module` and related tests to only take one signer. This change makes it so `moveth_minter` must have the same address as the module publisher. If I understand correctly, this will be okay to do because the plan is to implement a resource account pattern where the module is published under the resource account and the resource account is the minter. I may be …

fix bridge package publishing issue: init_module takes only 1 signer

---

protocol-units/bridge/move-modules/sources/MOVETH.move
protocol-units/bridge/move-modules/sources/atomic_bridge.move

Made it so minter role is removed after minting, so there doesn't accumulate an unneeded list of minters
* Added `remove_minter` function to `moveth` module
* Call `remove_minter` in `complete_bridge_transfer` after minting 
* Wrote test for someone already a minter calling `complete_bridge_transfer` (expected failure)
All unit tests pass.
Should be integration-tested with full concrete bridge implementation as we put it all together.

Improvements to complete_bridge_transfer flow, additional test added

---

Cargo.lock
Cargo.toml
protocol-units/execution/opt-executor/src/executor/initialization.rs

After https://github.com/movementlabsxyz/aptos-core/pull/45, the `rewards_apy_percentage` field in the genesis configuration is used to calculate the rewards without Movement-specific hacks, but this means it has to be set to 0 for our purposes.
* In the Aptos genesis configuration, the `rewards_apy_percentage` parameter is set to 0 to represent the reality of not using rewards on Aptos blockchain level.
Currently run tests should pass.

Update aptos-core, use 0 as the reward percentage

---

protocol-units/execution/opt-executor/Cargo.toml
protocol-units/execution/opt-executor/src/executor/mod.rs
protocol-units/execution/opt-executor/src/executor/transaction_pipe.rs
protocol-units/execution/opt-executor/src/lib.rs

When a mempool client request get passed with a oneshot callback,
the recipient of the callback may be dropped if the client
has cancelled the request. This condition should not be fatal
for the executor's transaction pipe.
`cargo test -p maptos-opt-executor`
Will add a test to exercise the non-fatal handling specifically.

Make cancellation of mempool request callbacks non-fatal

---

protocol-units/bridge/shared/README.mkd
protocol-units/bridge/shared/src/lib.rs
protocol-units/bridge/shared/src/multiple_sources_of_truth.rs

- **RFCs**: RFC040
This pull request introduces a new module `multiple_sources_of_truth` within the `bridge` component of the protocol units. This module is designed to manage multiple streams of input data, ensuring that event handling is based on consensus from multiple sources before considering the data as valid.
- Added a new module `multiple_sources_of_truth.rs` which encapsulates functionality for handling multiple sources of input.
- Updated `lib.rs` in the bridge component to include the new module.
The new module needs to be tested for:
1. Correct handling of events from multiple sources.
2. Event consensus mechanism validation.
3. Timeout and flush handling for unconfirmed events.
- Integration of the `multiple_sources_of_truth` module with …

ENG-671 Multiple Sources of Truth

---

networks/suzuka/suzuka-client/src/load_soak_testing/mod.rs
networks/suzuka/suzuka-client/src/load_soak_testing/scenario.rs

I've integrated the last modification of the load and soak FWk in one PR.
In suzuka-client/bin the demoscenario.rs file propose an example of soak test. To define a load test, remove the `config.kind = TestKind::Soak` config modification.
For load test, you can use the `LOADTEST_NUMBER_SCENARIO` and `LOADTEST_NUMBER_SCENARIO_PER_CLIENT` env var to define the load test configuration.
The soak test doesn't vary between min/max concurrent scenario but stay at the min level.

update with last version of the load and soak fwk

---

.github/workflows/checks.yml
Cargo.lock
protocol-units/execution/dof/Cargo.toml
protocol-units/execution/dof/src/v1.rs
protocol-units/execution/opt-executor/src/executor/transaction_pipe.rs

- **RFCs**: $\emptyset$
Adds mempool garbage collection on hard-coded 60 second interval. This should help with mempool load. 
1. Add `gc()` methods to `maptos-opt-executor`.
2. Call on interval in `dof-executor` background task. 
1. e2e tested. 
1. Should be added to the config perhaps. 
2. Mempool task spawning still deserves optimization.

Adds Garbage Collection on Interval for Mempool

---

.github/workflows/checks.yml
networks/suzuka/suzuka-full-node/src/partial.rs
protocol-units/da/m1/light-node/src/v1/sequencer.rs
protocol-units/execution/dof/src/lib.rs
protocol-units/execution/dof/src/v1.rs
protocol-units/execution/opt-executor/src/executor/initialization.rs
protocol-units/execution/opt-executor/src/executor/mod.rs
protocol-units/execution/opt-executor/src/executor/transaction_pipe.rs

- **Categories**: any of `protocol-units`
Implement load shedding for transaction flow.
In the current implement only `v1`, pardon the uninspiring naming, is considered. I think ideally, we would transform this such that we have an `enum TransactionLoadMilestone`, that we increment and decrement on relevant structs.
On the full-node, implement `v1` is fairly trivial, as we can report status directly to the client via the `MempoolRequest` API. I believe you may also be able to use the `commit_transaction` and `reject_transaction` API in a similar manner. But I have not yet confirmed.

Load Shedding

---

docker/compose/suzuka-full-node/docker-compose.celestia-local.yml
docker/compose/suzuka-full-node/docker-compose.yml

- **RFCs**: $\emptyset$
- **Categories**:  `networks`
Adds Restart Policies to Docker Compose application. Where this is used in infrastructure, adding these restart policies well prevent the entire application from being restarted by higher-order process managers. 
1. Adds appropriate restart policies by service. 
1. e2e testing. 
1. `docker-compose` files need some rewrites to better match `process-compose` files.

Adds Restart Policies to Docker Compose Application

---

.github/workflows/checks.yml
protocol-units/bridge/contracts/src/AtomicBridgeCounterparty.sol
protocol-units/bridge/contracts/src/AtomicBridgeInitator.sol
protocol-units/bridge/contracts/src/IAtomicBridgeCounterparty.sol
protocol-units/bridge/contracts/src/IAtomicBridgeInitiator.sol
protocol-units/bridge/contracts/test/AtomicBridgeCounterparty.t.sol
protocol-units/bridge/contracts/test/AtomicBridgeInitiator.t.sol

Creates the `AtomicBridgeCounterparty.sol` contract, tests and updates necessary logic in `AtomicBridgeInitiator.sol`. I added a storage mapping of balances in the Initiator contract. This is so that when users move MOVETH -> WETH they are able to withdraw their associated balance. We could have used a seperate Vault type contract, but I decided to keep it as simple as possible with minimal change necessary. 
Because of this, counterpary needs to call a withdraw function on Initiator, where the balances mapping is held. This function should of course only be callable by that contract and not by anyone, For this I added the ownable patter. To keep the contract upgradable, I used `UpgradableOwnable`.
- Creates new contract
- Creates new test
- Uses `UpgradableOwnable.sol` openzeppelin lib …

Create counterparty.sol contract

---

.github/scripts/update_move_toml.sh
.github/workflows/checks.yml
protocol-units/bridge/move-modules/Move.toml

Solution for [Issue #211](https://github.com/movementlabsxyz/movement/issues/211) to make Move tests run automatically in CI
* Add Move test workflow to `./github/workflows/checks.yml`
* Add `./github/scripts/update_move_toml.sh` script to run `aptos init` and update `Move.toml` with address generated
* Update `./protocol-units/bridge/move-modules/Move.toml` to use our fork of `aptos-core`
* All CI checks pass. 
* When I first ran the workflow successfully, it exposed a Move test failure which appears to have been due to using Aptos Labs' `aptos-core` GitHub repo as a dep, rather than our fork, hence updating `Move.toml` as part of this PR.
* Next iteration will replace Aptos CLI with Movement CLI. I'd like to first create more convenient installation options for Movement CLI such as …

Move tests run in CI

---

networks/suzuka/suzuka-config/src/execution_extension.rs
networks/suzuka/suzuka-config/src/lib.rs
networks/suzuka/suzuka-full-node/src/partial.rs

- **RFCs**: $\emptyset$
- **Categories**: any of `protocol-units`
Allows retries to be configured by config variables. 
1. Adds `execution_extension` config field to Suzuka config.
2. Adds retry fields to this extension. 
3. Applies them to the "partial" implementation. 
1. e2e testing. 
1. I think at this point we can change the "partial" naming.
2. The protocol this affects has a bit of a cascading effect, whereby increasing the timestamp of a block will mean that the next block has a greater likelihood of also needing to have its timestamp increased and with a greater number of retries. This will generally reset so long as the retry increment and count do not increases the timestamp beyond the block building time.

Retry Config

---

.github/workflows/checks.yml

Noticed these tests were not in our CI. At some point they failed and we did not catch it. It's important that this shared lib tests are always ran as the entire bridge service implementation is based off it. 
- Adds the tests for `bridge/shared/*` to our CI
- Runs in CI
None

Add shared bridge lib tests to CI

---

protocol-units/settlement/mcr/client/src/tests/e2e/test_client_settlement.rs

Coorect the e2e MRC build error.

correct mcr e2e test build

---

protocol-units/execution/opt-executor/src/executor/initialization.rs
protocol-units/execution/opt-executor/src/transaction_pipe.rs
protocol-units/execution/util/src/config/common.rs
protocol-units/execution/util/src/config/load_shedding.rs
protocol-units/execution/util/src/config/mod.rs

Lower the load shedding limit in the transaction ingress pipe task
to 12k.
* Maximum number of transactions in flight set to 12000.

fix(maptos-opt-executor): lower load shedding limit

---

protocol-units/execution/util/src/config/mod.rs

In `Deserialize` for top-level execution `Config`, default the `load_shedding` field if not present.
None added here, will test in infra.
Should we have example configs for testing regressions?

fix(maptos-execution-util): default load_shedding

---

networks/suzuka/setup/src/main.rs
networks/suzuka/suzuka-full-node/src/partial.rs
networks/suzuka/suzuka-full-node/src/tasks/execute_settle.rs
networks/suzuka/suzuka-full-node/src/tasks/transaction_ingress.rs
protocol-units/execution/dof/src/lib.rs
protocol-units/execution/dof/src/v1.rs
protocol-units/execution/opt-executor/src/executor/initialization.rs
protocol-units/execution/opt-executor/src/executor/mod.rs
protocol-units/execution/opt-executor/src/indexer.rs

1. Moves `BlobWriteRequest` submission back into an unawaited task, allowing the next blob batch to be constructed. 
2. Restores configuration for block retries.
1. e2e testing. 
1. I'm not 100% I caught everything. But, I think this is all of consequence that got dropped.

Restore Optimizations and Configuration Removed in Background Task Refactor

---

protocol-units/bridge/contracts/src/AtomicBridgeInitiator.sol
protocol-units/bridge/contracts/test/AtomicBridgeInitiator.t.sol
protocol-units/bridge/move-modules/sources/atomic_bridge_counterparty.move
protocol-units/bridge/move-modules/sources/atomic_bridge_initiator.move

- Fix for issue #458 for specific error codes on expected failure
- Replace block height with timestamp in initiator module
In `atomic_bridge_initiator.move`, the following test functions got a specific abort code and location:
- ` ``   
test_initiate_bridge_transfer_no_moveth
```
- ```    
test_complete_bridge_transfer_wrong_preimage
```
- ```    
test_refund_bridge_transfer
```
- ```    
test_refund_completed_transfer
```
- In initiator module, block height is replaced with timestamp. 
- Time passing is simulated with `aptos_framework::timestamp::fast_forwa;rd_seconds(time_lock + 2)`
- `refund_bridge_transfer` on Move side and `refundBridgeTransfer` can only be called by originator  / owner.
- Move unit tests pass.
- To verify, in `protocol-units/bridge/move-modules` run `movement move …
```

Feat: Move modules: `expected_failure` abort codes, replace block height with timestamp, refund assertions

---

.github/workflows/checks-all.yml
Cargo.lock
networks/suzuka/indexer/Cargo.toml
networks/suzuka/indexer/src/main.rs
util/dot-movement/src/lib.rs

To ease the test of the indexer as a standalone program, add the Config.json file creation if not present.
- Change dot-movement lib to add the function: try_get_or_create_config_from_json
- Activate the CI index test.
- Call the new function in the indexer main.rs.
-  Change indexer processor config file generation to tempfile, to avoid confusion with real config file.
To test: CELESTIA_LOG_LEVEL=FATAL nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash  -c "just suzuka-full-node native build.celestia-local.indexer.hasura.indexer-test --keep-tui"

Create the config file if not present when the indexer start.

---

protocol-units/settlement/mcr/contracts/src/staking/MovementStaking.sol
protocol-units/settlement/mcr/contracts/src/staking/MovementStakingStorage.sol
protocol-units/settlement/mcr/contracts/src/staking/interfaces/IMovementStaking.sol
protocol-units/settlement/mcr/contracts/test/staking/MovementStaking.t.sol

https://github.com/movementlabsxyz/movement/issues/529
Added a mapping between domain and bool to check if a genesis ceremony has been done for the specified domain.
Checks if running acceptGenesisCeremony() twice on the same domain reverts.
Clarify how a genesis ceremony could fail and ran again.

Genesis can only be ran once if successful per domain

---

protocol-units/README.md

- Updated `protocol-units` README to include all protocol unit categories
- Changed the numbered items to bullet points
Some of the "are members of this category" text I wrote could probably be improved by someone more intimitely familiar with all protocol units, but I believe the main gist of each category is represented.

Update protocol-units README.md

---

docker/compose/suzuka-full-node/docker-compose.yml

https://github.com/movementlabsxyz/infra/issues/163
Enable backtrace printouts on crashes of Movement services in docker-compose.

Set `RUST_BACKTRACE` for docker-compose services

---

protocol-units/bridge/move-modules/sources/MOVETH.move
protocol-units/bridge/move-modules/sources/atomic_bridge_counterparty.move
protocol-units/bridge/move-modules/sources/atomic_bridge_initiator.move
protocol-units/bridge/move-modules/sources/tests/MOVETH_tests.move

- There were dozens of Move compiler warnings. These have been cleaned up.
- Cleanup warnings generated in all Move modules
```
cd protocol-units/bridge/move-modules && movement move test
```
For future reference, imports that are only used in tests should have the `#[test_only]` attribute to avoid warnings.

Fix: Clean up Move compiler warnings

---

protocol-units/mempool/move-rocks/src/lib.rs

Fixes #322
Use `WriteBatch` to atomically update transaction column families in RocksDB mempool.
`cargo test -p move-rocks`
Existing tests should pass in CI.

Atomically update transaction mempool database

---

networks/suzuka/suzuka-client/src/tests/hey-partners/tests/typescript-sdk/package-lock.json
process-compose/suzuka-full-node/process-compose.setup.yml
protocol-units/execution/dof/src/v1.rs
protocol-units/execution/fin-view/src/fin_view.rs
protocol-units/execution/opt-executor/src/bootstrap.rs
protocol-units/execution/opt-executor/src/executor/execution.rs
protocol-units/execution/opt-executor/src/executor/initialization.rs
protocol-units/execution/opt-executor/src/executor/mod.rs
protocol-units/execution/opt-executor/src/service.rs
protocol-units/execution/opt-executor/src/transaction_pipe.rs
protocol-units/execution/util/src/config/chain.rs
protocol-units/execution/util/src/config/common.rs

Adds pruning config parameters for Aptos state  to the Maptos Config. Applies minimal defaults. Opens DB in pruning mode. 
1. All tests pass.
2. e2e testing for #369 sync speed shows improvement which reasonably facilitates testnet adoption, i.e., adoption against large states. 
1. Does not prune `suzuka-da-db` as this remains small. 
2. Does not add tests to confirm pruning behavior. These would have to be somewhat long-running; we will have to be cleverer about how we add these.

Elevate Pruning Config

---

protocol-units/da/m1/light-node/src/v1/sequencer.rs
protocol-units/mempool/move-rocks/src/lib.rs
protocol-units/mempool/util/src/lib.rs
protocol-units/sequencing/memseq/sequencer/src/lib.rs
protocol-units/sequencing/util/src/lib.rs

Fixes: #413
Add functionality to periodically iterate through RocksDB mempool transactions, earliest first, and delete transactions that have not made it into a block before the timestamp threshold. In the DA light node sequencer, use the heuristic of setting the threshold to twice the block building time.
* Perform periodic database sweeps to remove outdated transactions from the DA light node mempool.
TODO: add unit testing in mempool.
* Need to define a realistic e2e test scenario where this behavior could be verified.

Garbage collection in DA light node sequencer

---

Cargo.lock
Cargo.toml

- **Dependencies**: https://github.com/movementlabsxyz/aptos-core/pull/79
Integrate aptos-db patch to get log entries about merkle state db pruning.
* Added a few tracing events originating from the patched aptos_db crate,
to observe pruner behavior.
Checking logs of a running node.

deps: bump aptos-core to enable pruner tracing

---

protocol-units/bridge/move-modules/Move.toml
protocol-units/bridge/move-modules/sources/atomic_bridge_counterparty.move
protocol-units/bridge/move-modules/sources/atomic_bridge_initiator.move
protocol-units/execution/opt-executor/src/bootstrap.rs

fix: rename bridge modules to unbreak client tests
- updates naming that broke the tests
1. `aptos move test`
2. `cargo test --test client_movement_eth -- --nocapture --test-threads=1`
3. `cargo test --test client_eth_movement -- --nocapture --test-threads=1

fix: rename bridge modules to unbreak client tests

---

Cargo.lock
Cargo.toml
networks/suzuka/indexer/src/main.rs

Add the INDEXER_STARTING_VERSION environment variable to define the start version of the first Tx requested by the indexer when it starts.
CELESTIA_LOG_LEVEL=FATAL nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash  -c "just suzuka-full-node native build.setup.celestia-local.indexer.hasura.indexer-test --keep-tui"

Indexer add INDEXER_STARTING_VERSION env var

---

protocol-units/bridge/contracts/src/AtomicBridgeInitiatorMOVE.sol
protocol-units/bridge/contracts/test/AtomicBridgeInitiator.t.sol
protocol-units/bridge/contracts/test/AtomicBridgeInitiatorMOVE.t.sol

The solidity MOVE initiator contract was missing `transferFrom` call on the initiator side, these are present in the WETH contracts, so probably why we missed it.
- Adds the missing call
- Adds missing unit test logic
CI solidity-tests check should pass

fix: move erc20 transferFrom, update tests

---

docker/compose/suzuka-full-node/docker-compose.yml
docs/movement-node/run/manual/follower-node/README.md

`MAPTOS_CHAIN_ID` environment variable does not apply to compose services. This fixes that. 
Run `MAPTO_CHAIN_ID=250 just suzuka-full-node docker-compose local` with any recent container REV. Then assert that the chain id at `localhost:30731` is indeed 250.

Elevate Chain Id Config

---

flake.lock
flake.nix

bridge CI-CD runs fine
Updates forge-std to latest. Fixes to latest rev hash f533e2c70e520adb695c9917be21d514c15b1c4d
```
CELESTIA_LOG_LEVEL=FATAL CARGO_PROFILE=release CARGO_PROFILE_FLAGS=--release  nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash  -c "just bridge native build.setup.eth-local.celestia-local.bridge --keep-tui"
```

Fixes issue brought from #651

---

Cargo.lock
Cargo.toml
protocol-units/da/m1/light-node-grpc/Cargo.toml
protocol-units/da/m1/light-node-verifier/Cargo.toml
protocol-units/da/m1/light-node/Cargo.toml
protocol-units/da/m1/util/Cargo.toml

Remove tonic-web and tonic-reflection dependencies where they are not
required.
All targets should build with the dependencies pruned.

Remove excessive tonic dependencies

---

protocol-units/bridge/service/src/lib.rs
protocol-units/bridge/service/src/states.rs

Remove from the state management the transfer when it's finished
Remove transfer from state
implenents some todo in the state change processing.

Remove done transfer from state management.

---

protocol-units/mempool/move-rocks/src/lib.rs
protocol-units/mempool/util/src/lib.rs
protocol-units/sequencing/memseq/sequencer/src/lib.rs

Add logs to report when transactions get pruned from the sequencer's mempool.

Log transaction pruning in memseq

---

.github/workflows/build-push-containers-all.yml

- **Categories**:  `cicd`
1. Removes Helios Container Build from the CI Workflow.
2. Use of Helios `docker-compose` overlay should is now deprecated. 
1. Possibly provide alternative to `helios` overlay as `eth-remote` to more directly specify current usage.

Removes Helios Container Build from the CI Workflow

---

Cargo.lock
Cargo.toml
process-compose/suzuka-full-node/process-compose.feed.yml
process-compose/suzuka-full-node/process-compose.yml
protocol-units/bridge/service/Cargo.toml
scripts/services/bridge/build
scripts/services/m1-da-light-node/build
scripts/services/monza-full-node/build
scripts/services/suzuka-full-node/build
scripts/services/wait-for-celestia-light-node/build

- **Categories**: `scripts`.
* Reduce recompile-the-world tendencies by always selecting the package when building binaries (if the binaries need to be specifically selected at all, rather than just built as package's default targets).
* Fix cargo warnings.
* Cherry-pick a few process-compose changes from #697.

Fix local build scripts for process-compose

---

protocol-units/da/m1/light-node/src/v1/passthrough.rs
protocol-units/execution/opt-executor/src/gc_account_sequence_number.rs
protocol-units/execution/opt-executor/src/transaction_pipe.rs

1. Adds in sequence number fix that should have been part of #722 
2.  Adjusts logging for better control and debugging. 
1. e2e testing.

Local Run Errors

---

flake.lock
scripts/services/bridge/configure-bridge.sh

Creates a script for configuring the bridge relayer once it's running. Boolean arg sets whether move scripts should be run, as these are only required to be run once. 
Note that if they are run a second time on the same network an error will be thrown:
```
"Error": "Simulation failed with status: Move abort in 0x1::transaction_fee: ECOPY_CAPS_SHOT(0x7)
```
This is expected and it indicates the the user already has the mint and burn capabilities. 
1. Local suzuka-node should be running
2. At workspace root run 
`./scripts/services/bridge/configure-bridge.sh true`

feat: configure-bridge .sh

---

protocol-units/bridge/integration-tests/tests/client_eth_movement.rs
protocol-units/bridge/service/src/chains/ethereum/event_monitoring.rs
protocol-units/bridge/service/src/chains/movement/event_monitoring.rs
protocol-units/bridge/service/src/chains/movement/utils.rs

Change the Eth pulling to pull manual using RPC.

Bridge: change Eth monitoring to manual pull

---

Cargo.lock
Cargo.toml

- Framework at test rev (d9... enabling bypassing EIP-55 in the Movement-side `initiate_brige_transfer` call
- Other Aptos deps at the most recent rev (7a...)
- Should enable bridge FE to call `initiate_bridge_transfer` on the Movement side. Please test before merging.

bump aptos-core revision

---

networks/suzuka/indexer/bin/load_metadata.rs

Add the env var HASURA_ADMIN_AUTH_KEY to define the admin use by the update metadata request.
Add env var HASURA_ADMIN_AUTH_KEY
To update the Hasura metadata use this command in the movement root folder:
```
INDEXER_API_URL=https://indexer.testnet.porto.movementnetwork.xyz HASURA_ADMIN_AUTH_KEY=<admin key> POSTGRES_DB_HOST=postgres cargo run -p suzuka-indexer-service --bin load_metadata
```

Indexer: add admin key in as an env VAR: HASURA_ADMIN_AUTH_KEY

---

networks/suzuka/indexer/bin/load_metadata.rs
networks/suzuka/indexer/hasura_metadata.json

I've changed the env var to define the db URL entirely instead of the host.  The DB is now defined using POSTGRES_DB_URL
Example of commannd to update the indexer metadata:
```
INDEXER_API_URL=https://indexer.testnet.porto.movementnetwork.xyz HASURA_ADMIN_AUTH_KEY=<auth key> POSTGRES_DB_URL=postgres://<login>:<password>@<host>:5432/postgres cargo run -p suzuka-indexer-service --bin load_metadata
```

Indexer: add DB URL as env var and update metadata file

---

protocol-units/bridge/contracts/script/DeployAtomicBridgeInitiatorMOVE.s.sol
protocol-units/bridge/contracts/src/AtomicBridgeCounterparty.sol
protocol-units/bridge/contracts/src/AtomicBridgeCounterpartyMOVE.sol
protocol-units/bridge/contracts/src/AtomicBridgeInitiator.sol
protocol-units/bridge/contracts/src/AtomicBridgeInitiatorMOVE.sol
protocol-units/bridge/contracts/src/IAtomicBridgeCounterpartyMOVE.sol
protocol-units/bridge/contracts/test/AtomicBridgeCounterparty.t.sol
protocol-units/bridge/contracts/test/AtomicBridgeCounterpartyMOVE.t.sol
protocol-units/bridge/contracts/test/AtomicBridgeInitiator.t.sol
protocol-units/bridge/contracts/test/AtomicBridgeInitiatorMOVE.t.sol

Removes Pool Balance from eth contracts.
> cd /Users/user/movement/protocol-units/bridge/contracts
> forge test
There are tests that are failing in main branch. Disregard them

remove pool balance

---

protocol-units/bridge/integration-tests/tests/bridge_e2e_test.rs
protocol-units/bridge/integration-tests/tests/bridge_e2e_test_framework.rs
protocol-units/bridge/service/src/chains/ethereum/client.rs
protocol-units/bridge/service/src/chains/ethereum/utils.rs
protocol-units/bridge/setup/src/deploy.rs

Update eth send_transaction to set the from(signer_address) before gas_estimation.
Correct an issue where gas_estimation doesn't set correctly the sender and revert onlyOwner contract call.

Bridge: set from before gas_estimation

---

docs/movement-node/run/ansible/follower-node/suzuka-full-follower.yml
docs/movement-node/run/manual/follower-node/README.md

Resolves #785
- **Categories**: `docs`.
The documentation for the Follower Node is updated to reflect the renaming of services to the Bardock testnet.

Update follower node docs to use Bardock DNS names

---

protocol-units/bridge/integration-tests/tests/client_eth_movement.rs
protocol-units/bridge/service/src/actions.rs
protocol-units/bridge/service/src/chains/bridge_contracts.rs
protocol-units/bridge/service/src/chains/movement/utils.rs

- Adds a call to fund the Movement recipient when locking, so they have some funds to cover transaction fees when they call `complete_bridge_transfer`.
In `process_action` add a funding step before `lock_bridge_transfer` if the `recipient` field contains a 32-byte Movement address. This guarantees the recipient will have funds to to subsequently call `complete_bridge_transfer`.
Run bridge:
```
CELESTIA_LOG_LEVEL=FATAL CARGO_PROFILE=release CARGO_PROFILE_FLAGS=--release  nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash  -c "just bridge native build.setup.eth-local.celestia-local.bridge --keep-tui"
```
Then run the test:
```
DOT_MOVEMENT_PATH="$(pwd)/.movement" cargo test --test bridge_e2e_test_framework …
```

Feat: Fund Movement recipient

---

protocol-units/bridge/config/src/common/movement.rs
protocol-units/bridge/integration-tests/tests/bridge_e2e_test.rs
protocol-units/bridge/integration-tests/tests/bridge_grpc.rs
protocol-units/bridge/integration-tests/tests/bridge_rest.rs
protocol-units/bridge/service/src/lib.rs
protocol-units/bridge/service/src/main.rs
protocol-units/bridge/service/src/rest.rs

Issue: #774 
Add a task that runs every three minutes to ensure relayer is alive. 
Note that when I noticed the relayer going idle no errors were emitted and the health endpoint still responded 200, this is why I have chosen this approach, rather than checking health within docker setup.
Adds periodic wakeup task
This has to be observed over a 12 hour period in production, if the relayer continues to relay events after this time then the issue is resolved.

feat: keep relayer alive

---

Cargo.lock
Cargo.toml
flake.lock
flake.nix
protocol-units/da/m1/light-node-verifier/src/celestia/pessimistic.rs
protocol-units/da/m1/light-node/src/v1/passthrough.rs
protocol-units/da/m1/light-node/src/v1/sequencer.rs
protocol-units/da/m1/runners/src/celestia_bridge/local.rs
protocol-units/da/m1/setup/src/local.rs
protocol-units/da/m1/util/src/ir_blob.rs
scripts/services/suzuka-full-node/build

- **Categories**: `util`.
Update crate dependencies and local Celestia setup for latest stable (testnet) releases.
* Updated celestia crate dependency versions to 0.7.0.
`just suzuka-full-node native build.setup.eth-local.celestia-local.test`
* Can't fully verify yet because of a failure of the faucet readiness test.
* Bump crates to 0.7.0.

Update for celestia 0.17 / celestia-appd 2.3

---

Cargo.lock
Cargo.toml

Update the Aptos indexer version to the one that correct the chain_id issue.

Indexer: update aptos-indexer version to correct chain_id issue

---

.github/workflows/build-push-containers-all.yml
Cargo.lock
flake.nix
protocol-units/da/m1/light-node/src/v1/passthrough.rs
protocol-units/da/m1/setup/src/local.rs

- **RFCs**:  $\emptyset$.
Fixes Celestia orchestration bugs causing local process compose run to fail.

Resolve Process Compose Celestia Bug

---

docs/movement-node-experimental/l-monninger/open-network/README.md
docs/movement-node/run/ansible/follower-node/README.md
docs/movement-node/run/ansible/follower-node/suzuka-full-follower.service.j2
docs/movement-node/run/ansible/follower-node/suzuka-full-follower.yml

- **Categories**: `scripts`.
The follower node setup provisioned with Ansible is supposed to use the follower overlay, like in the README.

Fix up ansible/follower-node documentation and recipes

---

protocol-units/bridge/contracts/src/AtomicBridgeInitiatorMOVE.sol

- The protocol specifies that the initiator-side completeBridgeTransfer function should be onlyOwner. The initiator-side Move contract already has this in place. 
- Make completeBridgeTransfer onlyOwner in AtomicBridgeInitiatorMOVE.sol
CI should pass.

Make completeBridgeTransfer onlyOwner in AtomicBridgeInitiatorMOVE.sol

---

Cargo.lock
Cargo.toml
protocol-units/bridge/indexer-db/src/models.rs

- **Associated PR**: https://github.com/movementlabsxyz/aptos-core/pull/97
Resolves https://github.com/movementlabsxyz/movement/security/dependabot/12
by updating dependencies to use diesel >= 2.2.3
* Updated dependencies to fix GHSA-wq9x-qwcq-mmgf
CI tests should pass.

deps: bump diesel to 2.2, update aptos-core

---

protocol-units/execution/opt-executor/src/background/task.rs
protocol-units/execution/opt-executor/src/background/transaction_pipe.rs
protocol-units/execution/util/src/config/common.rs
protocol-units/execution/util/src/config/load_shedding.rs

- **RFCs**:$\emptyset$.
Makes inflight transaction limit optional in a manner which should be compatible with #839 . 
- Simply allows inflight transaction limit to be an option. If none, new transactions are always accepted. 
- This effectively pushes load-shedding down to the mempool garbage collection, which is undesirable because said subsystem will not be able to cleanly report `MempoolFull` to the client. So, #839 is preferred.
1. e2e testing.
1. Add automated e2e test covering restricted and non-restricted cases.

Make Inflight Limit Optional

---

protocol-units/settlement/mcr/contracts/src/settlement/MCR.sol
protocol-units/settlement/mcr/contracts/src/staking/MovementStaking.sol
protocol-units/settlement/mcr/contracts/src/staking/interfaces/IMovementStaking.sol

- Associated issues: #419
Adds reentrancy guards to `MCR` and `MovementStaking` contracts. 
1. Reentrancy guards in `MovementStaking` to address #419 . 
2. Addition of reentrancy guards where reentrancy is clearly not an intended behavior in `MCR`. 
1. `forge test` no changes made, passing. 
1. Add tests to replicate auditor discovered attacks. (May leave this as a draft until that is done.)

Reentrancy

---

protocol-units/bridge/contracts/foundry.toml
protocol-units/bridge/contracts/src/AtomicBridgeCounterpartyMOVE.sol
protocol-units/bridge/contracts/src/AtomicBridgeInitiatorMOVE.sol
protocol-units/bridge/contracts/src/RateLimiter.sol
protocol-units/bridge/contracts/test/AtomicBridgeCounterpartyMOVE.t.sol
protocol-units/bridge/contracts/test/AtomicBridgeInitiatorMOVE.t.sol

Atomic Bridge Rate Limiter
Added Rate Limiter contract that stores states on rate limiting.
Calls are made from permissioned atomic bridge contracts
cd bridge/contracts
forge test
Demonstrating that the rate limiting is valid throught time, but that's done on the other rate limiter.

Atomic Bridge Rate Limiter

---

Cargo.lock
Cargo.toml
protocol-units/bridge/setup/src/deploy.rs

Update the Aptos core framework rev to the one that include the @andygolay transfer_id serialization PR 105.
Correct a build issue in the bridge setup.
The bridge process compose starts now.
`CELESTIA_LOG_LEVEL=FATAL CARGO_PROFILE=release CARGO_PROFILE_FLAGS=--release nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash -c "just bridge native build.setup.eth-local.celestia-local.bridge --keep-tui`

Update aptos core rev and correct bridge setup build issue

---

protocol-units/bridge/integration-tests/tests/client_mvt_tests.rs
protocol-units/bridge/util/src/types.rs

- Addresses one point of https://github.com/movementlabsxyz/movement/issues/914, `client_mvt_tests test_movement_complete_transfer` (fixes `EINVALID_BRIDGE_TRANFER_ID` error in `test_movement_client_complete_transfer`)
- **Categories**: `bridge`
- Add helper function `normalize_to_32_bytes` to serialize `u64` the same way that's done on the Solidity side
- Update `test_movement_client_complete_transfer` to use the correct serialization
1. Run `CELESTIA_LOG_LEVEL=FATAL CARGO_PROFILE=release CARGO_PROFILE_FLAGS=--release nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash -c "just bridge native build.setup.eth-local.celestia-local.bridge.bridge-indexer --keep-tui"` to start the local Movement network
2. Run the integration test with …

Fix `test_movement_client_complete_transfer` so it passes, uses random nonce for test hardness

---

protocol-units/bridge/integration-tests/tests/bridge_e2e_test_framework.rs
protocol-units/bridge/service/src/actions.rs

- **Issue** #914 
- **Categories**: `bridge`, `E2E tests`
- Add `initiator.0 = hex::encode(initiator.0).into_bytes()` into `process_action` under `TransferActionType::CompleteBridgeTransfer` to convert Eth address into hex before feeding into `complete_bridge_transfer` due to hex encoding issue.
- Convert initiator data type to ASCII-encoded hex to compare initiator data after receiving Completed event
1. Run bridge with `CELESTIA_LOG_LEVEL=FATAL CARGO_PROFILE=release CARGO_PROFILE_FLAGS=--release nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash -c "just bridge native build.setup.eth-local.celestia-local.bridge.bridge-indexer --keep-tui"`
2. Run test with `RUST_BACKTRACE=1 DOT_MOVEMENT_PATH="$(pwd)/.movement" cargo test --test …

Feat: E2E Eth -> Movement happy path passes

---

Cargo.toml

Cleaned up the workspace configuration by removing duplicate entries from the `members` array in `Cargo.toml`.

remove duplicate entries Cargo.toml

---

Cargo.lock
Cargo.toml

By using `branch`, not `rev`, we remove the need to manually update and PR. This has been burdensome in some cases, now the workspace will always get the latest in `aptos-core/movement`.
Updates all aptos dependencies in Cargo.toml 
Build Succeeds

Remove need for manual updates from aptos-core

---

.github/workflows/checks-all.yml
Cargo.lock
Cargo.toml
protocol-units/bridge/integration-tests/src/lib.rs
protocol-units/bridge/integration-tests/tests/bridge_e2e_test_framework.rs
protocol-units/bridge/integration-tests/tests/client_eth_tests.rs
protocol-units/bridge/integration-tests/tests/client_mvt_tests.rs
protocol-units/bridge/service/src/actions.rs
protocol-units/bridge/service/src/chains/movement/client_framework.rs
protocol-units/bridge/service/src/chains/movement/utils.rs

- In `test_movement_client_complete_transfer`, add looping to event monitoring to get the correct `Initiated` event
- Remove `hex::encode()` of Eth initiator address in relayer
- Pass Eth initiator as bytes slice in integration and E2E tests.
- `test_movement_client_complete_transfer` and `test_bridge_transfer_eth_movement_happy_path` pass.
- Needs `aptos-core` rev from https://github.com/movementlabsxyz/aptos-core/pull/110 to be merged
- I guess we're waiting to merge the feature branch, and then we can merge this into main?

Remove initiator hex encoding from Movement client complete tests

---

Cargo.lock
Cargo.toml
protocol-units/bridge/integration-tests/src/lib.rs
protocol-units/bridge/integration-tests/tests/bridge_e2e_test_framework.rs
protocol-units/bridge/integration-tests/tests/client_mvt_tests.rs
protocol-units/bridge/service/src/chains/movement/client_framework.rs

- Client and E2E tests for MIP-58 bridge model: **RFCs**: https://github.com/movementlabsxyz/MIP/pull/58/
- Correct amount and account for bridge fee in `test_movement_client_initiate_transfer`
- Fixes flaky behavior in eth and movement event monitoring
- Due to the new bridge fee, there's a minimum amount. Here transfer amount is updated to 100 MOVE rather than 100 octas. (If Amount is 100 then that's 1*10^-7 MOVE, rather than 100 MOVE)
- A `get_bridge_fee` helper function calls the `native_bridge_configuration::bridge_fee()` Move function to be able to assert on the amount after `initiate_bridge_transfer` is called. 
- Fix normalization of 32 bytes to calculate correct bridge transfer ID
- Remove unneeded `MovementToEthCallArgs` and `EthToMovementCallArgs`
- Run local node with …

Fix `test_movement_client_initiate_transfer` and E2E tests

---

process-compose/bridge/process-compose.yml

- The `movement-full-node` command was updated in main. This PR updates the bridge .yml scripts.
```
CELESTIA_LOG_LEVEL=FATAL CARGO_PROFILE=release CARGO_PROFILE_FLAGS=--release nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash -c "just bridge native build.setup.eth-local.celestia-local.bridge.bridge-indexer --keep-tui
```

Fix bridge process-compose links

---

protocol-units/bridge/move-modules/scripts/store_mint_burn_caps.move
protocol-units/bridge/move-modules/scripts/update_bridge_fee.move
protocol-units/bridge/move-modules/scripts/update_bridge_relayer.move

- Make calls to `native_bridge` module only, rather than `native_bridge_core` or `native_bridge_configuration`
- movement move compile --package-dir protocol-units/bridge/move-modules

Fix Move scripts so they compile

---

Cargo.toml

Clean up outdated Ethereum library dependencies from `Cargo.lock`.
Everything still builds.

Remove unused Ethereum deps

---

docker/build/wait-for-celestia-light-node/Dockerfile

Use alpine for base image for wait for sync image too.
This is needed to create kubernetes liveliness and readiness probes using bash commands

Use alpine for base image for wait for sync image too

---

protocol-units/bridge/contracts/src/INativeBridge.sol
protocol-units/bridge/contracts/src/NativeBridge.sol
protocol-units/bridge/contracts/test/NativeBridge.t.sol

Because we will be switching to Inbound Rate Limiting only, moving the Outbound Rate Limiting to the Move side of the bridge, we needed to remove the outbound rate limiter locally.
This PR also addresses Rate Limiting concerns raised on feature/trusted-relayer
- Removal of OutboundRateLimiter
- setRiskDenominator
- Rate Limiting Tests including change of denominator

Only Inbound Rate Limiting 

---

Cargo.lock
demo/hsm/Cargo.toml
demo/hsm/src/hsm/aws_kms.rs
demo/hsm/src/hsm/cli.rs
demo/hsm/src/hsm/hashi_corp_vault.rs
demo/hsm/src/lib.rs
demo/hsm/src/main.rs
demo/hsm/src/server.rs

- Add server and make main send transactions to the server.
- Runs and signs a few hard-coded messages
- Temporarily don't run `Application` with `random_stream` in `https://github.com/movementlabsxyz/movement/blob/l-monninger/hsm-demo/demo/hsm/src/main.rs`. Instead send a few hard-coded messages to the server for signing.
- `cargo run`
- Restore `Application` with `random_stream` for demonstration purposes

Server for HSM demo

---

Cargo.lock
Cargo.toml

Fixes #876
Follow up to #937, locking revisions of the updated dependencies to be on `main` in each of the repositories.

deps: update bcs, aptos-core, aptos-indexer-processors

---

util/signing/signing-admin/src/cli/rotate_key.rs

As configuration for the rotate-key subcommand of signing-admin,
`VAULT_URL` was not the conventional way to specify the Vault URL.

Use `VAULT_ADDR` environment variable to configure `signing-admin rotate-key`

---

util/syncador/src/backend/archive/gzip/mod.rs
util/syncador/src/backend/archive/gzip/pull.rs
util/syncador/src/backend/archive/gzip/push.rs
util/syncador/src/backend/s3/shared_bucket/mod.rs
util/syncador/src/backend/s3/shared_bucket/pull.rs
util/syncador/src/backend/s3/shared_bucket/push.rs
util/syncador/src/files/package/mod.rs

PR to test the leader sync file split in smaller chunks to avoid S3 transfer too big file error.
To test with current burdock rev.

[test]- Split leader archive file in smaller chunk.

---

Cargo.lock
networks/movement/movement-full-node/Cargo.toml
networks/movement/movement-full-node/src/da/stream_blocks/mod.rs
networks/movement/movement-full-node/src/node/tasks/execute_settle.rs
process-compose/movement-full-node/process-compose.test-followers.yml
proto/movementlabs/protocol_units/da/light_node/v1beta2.proto
protocol-units/da/movement/protocol/light-node/src/passthrough.rs
protocol-units/da/movement/protocol/proto/build.rs
protocol-units/da/movement/protocol/proto/src/lib.rs
protocol-units/da/movement/protocol/util/src/config/common.rs

Add a Heartbeat on the DA stream from the leader to the follower.
* Integrate DA changes from PR #996.
* Add heartbeat on the the DA stream.
To test run the command:
```
CELESTIA_LOG_LEVEL=FATAL nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash  -c "just movement-full-node native build.setup.eth-local.celestia-local.test-followers --keep-tui"
```
You can update the `test-followers` overlay so that the test never end and you'll see on each follower the heartbeat notification.

[Node] Correct DA stream timeout error.

---

protocol-units/da/movement/protocol/celestia-runners/src/celestia_light/arabica.rs
protocol-units/da/movement/protocol/celestia-runners/src/celestia_light/mainnet.rs
protocol-units/da/movement/protocol/celestia-runners/src/celestia_light/mocha.rs
protocol-units/da/movement/protocol/setup/src/common/celestia.rs
protocol-units/da/movement/protocol/util/src/config/default.rs
protocol-units/da/movement/protocol/util/src/config/light.rs
util/commander/src/lib.rs

Add a configuration field for the `--node.store` parameter passed to the light node runner.
The default is overridable with the `CELESTIA_LIGHT_NODE_STORE` environment variable.
`commander` gets its own `Command` wrapper to improve ergonomics.

Config parameter for celestia light node store directory

---

Cargo.lock
protocol-units/da/movement/protocol/client/Cargo.toml
protocol-units/da/movement/protocol/client/src/lib.rs
util/godfig/src/backend/config_file/mod.rs
util/godfig/src/backend/mod.rs
util/signing/interface/src/key/mod.rs

- 
Sometime during the docker container start, the full node start too early and the DA light node didn't have opened its entry point. It results in an error during the full node start, then a restart of the whole stack.
This scenario can repeat several times until the timing is correct.
This PR add a retry for this connection so that full node start is less sensible to timing issues during the start.
I've changed the error message when the config can't be parsed.
* Ad a retry when the Http2 connection fails during init. 
* add a better error message when the config can't be parsed
* 
To test, you can start a …

[Node] Add retry on DA connection

---

.gitignore
protocol-units/settlement/mcr/contracts/script/DeployMCRDev.s.sol
protocol-units/settlement/mcr/contracts/src/settlement/MCR.sol
protocol-units/settlement/mcr/contracts/src/settlement/MCRStorage.sol
protocol-units/settlement/mcr/contracts/src/staking/MovementStaking.sol
protocol-units/settlement/mcr/contracts/src/staking/interfaces/IMovementStaking.sol
protocol-units/settlement/mcr/contracts/test/settlement/MCR.sol
protocol-units/settlement/mcr/contracts/test/staking/MovementStaking.t.sol

Rewards for the Attesters as long as they attested before the postconfirmation
- adds reward functionality, specifically updates `rollOverEpoch`
- split payAttester into specialized functions
- adds tests
- testRewardSingleAttester
- setupGenesisWithOneAttester
- testRewardPoints
- testPostconfirmationRewards
`forge test` ok
- postconfirmation should be delayed compared to first honest commit

[postconfirmation] attester rewards

---

docker/compose/movement-full-node/docker-compose.celestia-mainnet.yml

- **Categories**: `scripts`.
* Point to the consensus node in the infra.
* Specify the listen address for the RPC.
* Pass the `NODE_STORE` environment variable so that the endpoint calls init on the store.
* Improve the health check to check the service port with nc.

fix(docker): celestia-light-node fixes

---

networks/movement/indexer/src/main.rs

* add ANS processor
* Change ACTIVATE_TOKEN_INDEXING env var behaviour: if not defined use the current height
To start the indexer and see if it indexes some TX:
```
CELESTIA_LOG_LEVEL=FATAL nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash  -c "just movement-full-node native build.setup.eth-local.celestia-local.indexer --keep-tui"
```

[Indexer] Add ans processor

---

Cargo.lock
protocol-units/da/movement/protocol/util/src/blob/ir/blob.rs
protocol-units/execution/maptos/opt-executor/src/executor/execution.rs
util/signing/testing/Cargo.toml
util/signing/testing/tests/execute.rs

Reverting the LocalAccount initialization to the way it was done before remote signing (#993) was merged makes the tests pass, though I don't yet understand why.
```
nix develop --extra-experimental-features "nix-command flakes" --command bash -c "cargo test -p maptos-opt-executor"
```
Why does use of `aptos_test_root_address()` make the transactions be accepted by the executor, while the address and the signing key don't actually match?

test: fix unit tests

---

protocol-units/da/movement/protocol/client/Cargo.toml
protocol-units/da/movement/protocol/client/src/http2.rs

The DA client htp2 connection code wasn't merge in main. Put it back.

[Follower] Correct DA client http2 connection

---

networks/movement/movement-full-node/src/da/stream_blocks/mod.rs

The DA tool should use `http2` not `http1`.
```
./target/debug/movement-full-node da stream-blocks https://m1-da-light-node.mainnet.movementnetwork.xyz/ 4315164
2025-03-05T23:05:45.654626Z  INFO movement_full_node::da::stream_blocks: streaming blocks from DA
2025-03-05T23:05:45.655956Z  INFO movement_full_node::da::stream_blocks: Receive heartbeat blob
2025-03-05T23:05:46.917033Z  INFO movement_full_node::da::stream_blocks: Receive PassedThroughBlob blob
2025-03-05T23:05:46.917858Z  INFO movement_full_node::da::stream_blocks: Block ID: bfbd27af2c32a36b4fb96bbe489598189974fa5aaf121086a89e4ffe70489015, Block Timestamp: 2025-03-05T23:05:34.458688Z, DA Height: 4315166
```

HTTP2 Connection Should be Used for DA Tool

---

networks/movement/movement-full-node/src/node/tasks/execute_settle.rs

- **Categories**: `networks`.
Remove a duplicate "execute_block" tracing span and ensure the remaining span shows a nice hex-encoded block_id value.

fix: deduplicate execute_block tracing spans

---

protocol-units/da/movement/protocol/light-node/src/sequencer.rs
protocol-units/mempool/move-rocks/src/lib.rs
protocol-units/sequencing/memseq/sequencer/src/lib.rs

Sundry fixes to address the observed performance:
- Disable GC in rocksdb-mempool, which does not work correctly.
- Rework a busy loop in memseq.
- Code change to remove contention in rocksdb-mempool.

fix: quick fixes for DA sequencer

---

protocol-units/da/movement/protocol/light-node/src/sequencer.rs
protocol-units/sequencing/memseq/sequencer/src/lib.rs
util/movement-types/src/block.rs

Submits Celestia blobs in parallel. This resolves backpressuring and works in the context where you rely on Celestia for ordering. When Celestia is no longer used for ordering, e.g., WAL-Celestia, you will need to return to some kind of sequential submission to make sure these match. 
Also adds `submit_collapsed_block` to replace submission in parallel with submission of single batched block. This works under both ordering and non-ordering regimes of Celestia given submissions over the in-process channel are read and processed in order.

Memseq Degradation

---

protocol-units/da/movement/protocol/light-node/src/passthrough.rs
protocol-units/da/movement/protocol/light-node/src/sequencer.rs

Replace unimplemented panics on gRPC endpoints
with gRPC status returns.

fix(da-light-node): graceful return on unimlemented

---

Cargo.lock
networks/movement/movement-full-node/Cargo.toml
networks/movement/movement-full-node/src/node/partial.rs
networks/movement/movement-full-node/src/node/tasks/transaction_ingress.rs
protocol-units/da/movement/protocol/light-node/src/sequencer.rs
protocol-units/execution/maptos/util/src/config/common.rs
protocol-units/execution/maptos/util/src/config/load_shedding.rs
protocol-units/sequencing/memseq/util/src/lib.rs

- add a specific config parameter for batch production loop
- decrease the Da light node block creation timing loop.
- - remove 0.3.3 Celestia //  task patch.
Set the rapport between of full node batch creation and Da light node block creation to 4 by default.
To deploy this version on Testnet or mainnet the new config param will need to be added. This section should be update as follow, the batch_production_time should be added to the section load_shedding like this example:
```
"load_shedding": {
"max_transactions_in_flight": null,
"batch_production_time": 2000
},
```
And the `memseq_build_time` should be …

Fix: change batch creation loop timing paramter.

---

CHANGELOG.md
Cargo.lock
Cargo.toml
networks/movement/movement-client/Cargo.toml
networks/movement/movement-client/src/bin/e2e/bardock_alice_bob.rs
networks/movement/movement-full-node/Cargo.toml
networks/movement/movement-full-node/src/node/partial.rs
networks/movement/movement-full-node/src/node/tasks/transaction_ingress.rs
protocol-units/da/movement/protocol/light-node/src/passthrough.rs
protocol-units/da/movement/protocol/light-node/src/sequencer.rs
protocol-units/execution/maptos/util/src/config/common.rs
protocol-units/execution/maptos/util/src/config/load_shedding.rs
protocol-units/sequencing/memseq/util/src/lib.rs

We may want to have this functionality, but it wasn't thoroughly e2e tested and the parallelism caused a bottleneck at DA block production rate. 
For now this removes that feature from main and we can reopen the #1110 PR
This PR removed commit `1cec33a2df0510c6e789998d7e0dd2d5ee49893b` using the interactive rebase method from main. Doing so re-commits all the changes after that PR hence the diff.
Removes the logic added 
cargo checks and builds

chore: remove #1110 from main 

---

protocol-units/da-sequencer/node/src/celestia/mod.rs
protocol-units/da-sequencer/node/src/storage/mod.rs

Define trait for the Storage and Celestia client to allow to Mock them for the test.
It provides on the trait definition. Implementation will be done in future PR.
* Add `DaSequencerStorage` trait
* Add `DaSequencerExternDaClient` trait

feat: Add traits for Storage and Celestia client

---

Cargo.lock
protocol-units/da-sequencer/client/Cargo.toml
protocol-units/da-sequencer/client/src/lib.rs
protocol-units/da-sequencer/config/Cargo.toml
protocol-units/da-sequencer/config/src/lib.rs
protocol-units/da-sequencer/node/Cargo.toml
protocol-units/da-sequencer/node/src/batch.rs
protocol-units/da-sequencer/node/src/celestia/mod.rs
protocol-units/da-sequencer/node/src/error.rs
protocol-units/da-sequencer/node/src/lib.rs
protocol-units/da-sequencer/node/src/main.rs
protocol-units/da-sequencer/node/src/server.rs
protocol-units/da-sequencer/node/src/storage/mod.rs
protocol-units/da-sequencer/node/src/tests/mock.rs
protocol-units/da-sequencer/node/src/tests/mod.rs

- 
Implementation of the issue #1135. Connect write_batch to the da storage.
Start implementing the mainloop.
Add Storage and Celestia mock.
* Call storage's write_batch
* Start implementing the main loop
* Update Celestia and storage trait.
*  Create Storage and Celestia mock
* Add a submit_batch test
* Start main.rs impl.
To start the submit_batch test run
```
RUST_LOG=info cargo test -p movement-da-sequencer-node test_write_batch_gprc_main_loop
```

da-sequencer: Connect grpc write_batch to the storage.

---

networks/movement/movement-full-node/src/node/tasks/execute_settle.rs
proto/movementlabs/protocol_units/da/sequencer/v1.proto
protocol-units/da-sequencer/client/src/lib.rs
protocol-units/da-sequencer/node/src/server.rs
protocol-units/da-sequencer/proto/build.rs
protocol-units/da-sequencer/proto/src/lib.rs
protocol-units/execution/maptos/opt-executor/src/background/transaction_pipe.rs

Bring the sequencer proto file in conformance with common proto
evolution conventions.
No minor and patch versioning in package name is necessary: v1 will
evolve backward-compatibly until there's time for a v2.
Style nit: no da-da repetition in the package name and paths.

fix(da-sequencer): style improvements for sequencer proto

---

Cargo.lock
protocol-units/da-sequencer/client/Cargo.toml
protocol-units/da-sequencer/client/src/lib.rs
protocol-units/da-sequencer/config/src/lib.rs
protocol-units/da-sequencer/node/src/tests/client.rs

- Addresses part of issue #1169 
- Update `GrpcDaSequencerClient` struct and impl with heartbeat alert transmission channel and heartbeat interval for configurability
- Update `stream_read_from_height` to check for two missed heartbeats and send an alert
- Add two tests of the alert system
- Currently the stream does not stop when the alert happens.
Individual tests:
- `cargo test test_missed_grpc_heartbeat_twice_triggers_alert -lib -p movement-da-sequencer-node`
- `cargo test test_missed_grpc_heartbeat_once_does_not_trigger_alert -lib -p movement-da-sequencer-node`
Or run all crate tests:
- `cargo test -p movement-da-sequencer-node`
- How should `stream_read_from_height` handle if the alert happens?

feat: gRPC client heartbeat detection and alert

---

protocol-units/da-sequencer/config/src/lib.rs
protocol-units/da-sequencer/node/src/block.rs
protocol-units/da-sequencer/node/src/celestia/blob.rs
protocol-units/da-sequencer/node/src/celestia/client.rs
protocol-units/da-sequencer/node/src/celestia/height.rs
protocol-units/da-sequencer/node/src/celestia/mod.rs
protocol-units/da-sequencer/node/src/celestia/submit.rs
protocol-units/da-sequencer/node/src/lib.rs
protocol-units/da-sequencer/node/src/main.rs
protocol-units/da-sequencer/node/src/server.rs
protocol-units/da-sequencer/node/src/storage/mod.rs
protocol-units/da-sequencer/node/src/tests/mock.rs
protocol-units/syncing/syncup/src/lib.rs
util/movement-types/src/block.rs
util/signing/providers/hashicorp-vault/src/hsm/mod.rs

- #1158 
- **Categories**: `protocol-units`, `da-sequencer`
- Remove the block height from the Celestia blob.
- Store an array of block `Id`s in the Celestia blob.
- Remove `SequencerBlockDigest` altogether.
- Resolve all compiler warnings.
To run the test, run the cmd:
```
cargo test -p movement-da-sequencer-node 
```
Since we no longer store the block height in the Celestia blob, we need to ensure that all block IDs in the blobs are strictly sequential concerning the block height. The batching algorithm must uphold this invariant.

feat[da-sequencer]: remove block height from the Celestia blob

---

protocol-units/da-sequencer/node/src/celestia/mod.rs

- #1158 
- **Categories**: `protocol-units`, `da-sequencer`
- Implement the missing `request_block_with_id(block::Id)` function.
- Add `ExternalDaNotification::RequestBlockForId`
- Improve the documentation in the comments.
To run the test, run the cmd:
```
cargo test -p movement-da-sequencer-node 
```

feat[da-sequencer]: Implement request block with id

---

protocol-units/da-sequencer/node/src/server.rs

Clean up unnecessary locking and `Arc` on the whitelist field of the da-sequencer server.

refactor(da-sequencer): no lock, Arc on whitelist

---

flake.lock
flake.nix
rust-toolchain.toml

Build times seem significantly improved on Rust 1.85. Opening this PR to use it going forward. 
- e2e tests

feat: rust 1.85

---

networks/movement/movement-client/src/tests/complex-alice/Move.toml
networks/movement/movement-client/src/tests/complex-alice/deploy.sh
networks/movement/movement-client/src/tests/hey-partners/test.sh
networks/movement/movement-client/src/tests/mod.rs
process-compose/movement-full-node/process-compose.complex-alice-load.yml
process-compose/movement-full-node/process-compose.complex-alice-soak.yml
process-compose/movement-full-node/process-compose.hey-partners-load.yml
process-compose/movement-full-node/process-compose.hey-partners-soak.yml
protocol-units/da/movement/protocol/light-node/src/sequencer.rs

This PR fixes the block proposer channel buffer size in the light-node sequencer by replacing the incorrect exponentiation (using the XOR operator) with a correct computation via a constant.
- Fixed the channel buffer size creation by introducing BLOCK_PROPOSER_CHANNEL_BUFFER_SIZE.
- Updated the usage of the channel constructor to use the new constant.

fix[da-light-node]: fix block proposer buffer size

---

protocol-units/da-sequencer/node/src/server.rs
protocol-units/execution/maptos/opt-executor/src/background/transaction_pipe.rs

If the da-sequencer rejects the full node batch, the full node crashes.
Remove the panic to avoid the node to  crash and only log a warning.

Bug, warn on batch rejected by the da sequencer.

---

Cargo.lock
Cargo.toml

Remove most of the panic to [the indexer code](https://github.com/movementlabsxyz/aptos-indexer-processors/pull/11).
to test to start the indexer:
```
CELESTIA_LOG_LEVEL=FATAL MOVEMENT_PREBUILT=false nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash  -c "just movement-full-node native build.setup.eth-local.celestia-local.indexer.hasura.indexer-test --keep-tui"
```

Bug, update indexer commit rev to link the remove panic one

---

networks/movement/movement-full-node/src/main.rs

updated full node to have tracing initialization independent of aptos-telemetry
modified `main.rs` in `movement-full-node`

fix: initialize individual tracing for full node

---

flake.nix

- **Categories**: `scripts`
Fixes a bug in the Nix `shellHook` that caused the dev shell to attempt executing `x86_64-linux` as a shell command, resulting in:
```
bash: x86_64-linux: command not found
```
- Fixed a bug in `flake.nix` where the dev shell attempted to execute the platform string as a command (`x86_64-linux`), causing startup errors.
Locally tested and looks good.

[script] fix the system env check in nix script.
